<?php

/**
 * Generated by scripts/block-strings.mjs. Do not edit: run `npm run translate:blocks`.
 * Block setting defaults, listed so translation tools can find them. Never loaded at runtime.
 */

// phpcs:disable -- generated extraction list.
return static function () {
    /* translators: Default for the Signature Dishes block setting "eyebrow". */
    __('Signature dishes', 'cobbleandcandle');
    /* translators: Default for the Signature Dishes block setting "title". */
    __('Signatures of the house', 'cobbleandcandle');
    /* translators: Default for the Signature Dishes block setting "intro". */
    __('Three plates that have stayed on the menu through every season, because guests would riot otherwise.', 'cobbleandcandle');
    /* translators: Default for the Contact Form block setting "eyebrow". */
    __('Contact', 'cobbleandcandle');
    /* translators: Default for the Contact Form block setting "title". */
    __('Write to us', 'cobbleandcandle');
    /* translators: Default for the Contact Form block setting "intro". */
    __('For bookings within 48 hours please call the house directly. Everything else, drop us a line and we’ll reply within one working day.', 'cobbleandcandle');
    /* translators: Default for the Contact Form block setting "contacts". */
    __('Press: press@example.com
Careers: jobs@example.com
Gift cards & lost property: Ask any house, or use the form.', 'cobbleandcandle');
    /* translators: Default for the Event Details block setting "notes". */
    __('Dietary needs can be accommodated with 72 hours’ notice.
Tickets are refundable up to 7 days before.
Ages 18+.', 'cobbleandcandle');
    /* translators: Default for the Events Archive block setting "listTitle". */
    __('All upcoming', 'cobbleandcandle');
    /* translators: Default for the Events Archive block setting "emptyText". */
    __('Nothing on the calendar just now. Check back soon.', 'cobbleandcandle');
    /* translators: Default for the Events Archive block setting "regularsEyebrow". */
    __('Every week', 'cobbleandcandle');
    /* translators: Default for the Events Archive block setting "regularsTitle". */
    __('Regulars & specials', 'cobbleandcandle');
    /* translators: Default for the Events Archive block setting "regularsIntro". */
    __('Chalked up fresh each day at every house.', 'cobbleandcandle');
    /* translators: Default for the Events Archive block setting "regulars". */
    __('Two-course weekday lunch from $34
Half-price bottles on Sunday evenings
Seasonal set menu, Tuesday to Thursday', 'cobbleandcandle');
    /* translators: Default for the Events Archive block setting "boardEyebrow". */
    __('By the glass', 'cobbleandcandle');
    /* translators: Default for the Events Archive block setting "boardTitle". */
    __('Tonight’s Cellar', 'cobbleandcandle');
    /* translators: Default for the Events Archive block setting "boardFoot". */
    __('Ask your sommelier', 'cobbleandcandle');
    /* translators: Default for the Upcoming Events block setting "eyebrow". */
    __('Events & specials', 'cobbleandcandle');
    /* translators: Default for the Upcoming Events block setting "title". */
    __('What’s on', 'cobbleandcandle');
    /* translators: Default for the Upcoming Events block setting "intro". */
    __('Suppers, music and seasonal nights across all three houses.', 'cobbleandcandle');
    /* translators: Default for the Upcoming Events block setting "linkLabel". */
    __('All events', 'cobbleandcandle');
    /* translators: Default for the Full Menu block setting "allergenNote". */
    __('Please tell your server about any allergies before ordering. Our kitchens handle nuts, gluten and shellfish; we cannot guarantee any dish is allergen-free.', 'cobbleandcandle');
    /* translators: Default for the Full Menu block setting "orderTitle". */
    __('Order online', 'cobbleandcandle');
    /* translators: Default for the Full Menu block setting "orderText". */
    __('Collect from any of our houses from 5pm.', 'cobbleandcandle');
    /* translators: Default for the Gallery Mosaic block setting "eyebrow". */
    __('Gallery', 'cobbleandcandle');
    /* translators: Default for the Gallery Mosaic block setting "title". */
    __('Inside the houses', 'cobbleandcandle');
    /* translators: Default for the Gallery Mosaic block setting "linkLabel". */
    __('View the gallery', 'cobbleandcandle');
    /* translators: Default for the Hero block setting "caption". */
    __('Chandler’s Wharf at dusk', 'cobbleandcandle');
    /* translators: Default for the Hours Strip block setting "tonightNote". */
    __('Tonight’s seatings · 6:00 & 8:30', 'cobbleandcandle');
    /* translators: Default for the Houses block setting "eyebrow". */
    __('Our houses', 'cobbleandcandle');
    /* translators: Default for the Houses block setting "title". */
    __('Find your table', 'cobbleandcandle');
    /* translators: Default for the Location Details block setting "reserveLabel". */
    __('Reserve a table', 'cobbleandcandle');
    /* translators: Default for the Locations Explorer block setting "reserveLabel". */
    __('Reserve a table', 'cobbleandcandle');
    /* translators: Default for the Menu Teaser block setting "eyebrow". */
    __('The menu', 'cobbleandcandle');
    /* translators: Default for the Menu Teaser block setting "title". */
    __('From the bill of fare', 'cobbleandcandle');
    /* translators: Default for the Menu Teaser block setting "intro". */
    __('Our menus are written each morning and printed on the press in the cellar.', 'cobbleandcandle');
    /* translators: Default for the Menu Teaser block setting "boardEyebrow". */
    __('By the glass', 'cobbleandcandle');
    /* translators: Default for the Menu Teaser block setting "boardTitle". */
    __('Tonight’s Cellar', 'cobbleandcandle');
    /* translators: Default for the Menu Teaser block setting "boardFoot". */
    __('Ask your sommelier', 'cobbleandcandle');
    /* translators: Default for the Page Not Found block setting "eyebrow". */
    __('Error 404 · Page not found', 'cobbleandcandle');
    /* translators: Default for the Page Not Found block setting "title". */
    __('This lane is unlit.', 'cobbleandcandle');
    /* translators: Default for the Page Not Found block setting "text". */
    __('The page you were after has slipped down a side street. Let us light the way back.', 'cobbleandcandle');
    /* translators: Default for the Reservations block setting "notes". */
    __('Tables are held for 15 minutes.
Cancel free up to 24 hours before.
Parties of 9 or more: ask about private dining.
Tell us about allergies when booking.
Smart-casual; no dress code.', 'cobbleandcandle');
    /* translators: Default for the Reservations block setting "callHours". */
    __('Phones answered daily 11am – 6pm. Walk-ins always welcome at the bar.', 'cobbleandcandle');
    /* translators: Default for the Reviews & Press block setting "eyebrow". */
    __('Reviews & press', 'cobbleandcandle');
    /* translators: Default for the Reviews & Press block setting "title". */
    __('Kind words', 'cobbleandcandle');
    /* translators: Default for the Reviews & Press block setting "press". */
    __('The Old Town Courier, Harbour & Hearth, Coastal Table, The Night Ledger', 'cobbleandcandle');
    /* translators: Default for the Room Details block setting "notes". */
    __('Check-in from 3pm, check-out by 11am.
Cooked breakfast served 8–10am in the bar.
Free cancellation up to 7 days before arrival.', 'cobbleandcandle');
    /* translators: Default for the Rooms block setting "eyebrow". */
    __('Stay with us', 'cobbleandcandle');
    /* translators: Default for the Rooms block setting "title". */
    __('Rooms upstairs', 'cobbleandcandle');
    /* translators: Default for the Rooms block setting "intro". */
    __('Sleep above the tavern. Breakfast is on us.', 'cobbleandcandle');
    /* translators: Default for the Rooms block setting "linkLabel". */
    __('All rooms', 'cobbleandcandle');
    /* translators: Default for the Rooms block setting "emptyText". */
    __('Rooms are being readied. Call us to book a stay.', 'cobbleandcandle');
    /* translators: Default for the Site Header block setting "reserveLabel". */
    __('Reserve a table', 'cobbleandcandle');
    /* translators: Default for the Site Header block setting "orderLabel". */
    __('Order online', 'cobbleandcandle');
    /* translators: Default for the Story block setting "caption". */
    __('Margot Ellery · Chef-patron since 2014', 'cobbleandcandle');
    /* translators: Default for the Timeline block setting "eyebrow". */
    __('Since 1888', 'cobbleandcandle');
    /* translators: Default for the Timeline block setting "title". */
    __('A short history', 'cobbleandcandle');
    /* translators: Default for the Timeline block setting "items". */
    __('1888 | The first supper | Lamplighter Josiah Wren opens his parlour to the evening tide.
1931 | The cellar opens | The old coal store becomes a wine cellar of 400 bins.
1998 | Cathedral Close | A second house opens in a former vestry beside the cathedral.
2014 | Chef Margot | Margot Ellery takes the pass and rewrites the bill of fare.', 'cobbleandcandle');
    /* translators: Default for the Values block setting "eyebrow". */
    __('What we believe', 'cobbleandcandle');
    /* translators: Default for the Values block setting "title". */
    __('House rules', 'cobbleandcandle');
    /* translators: Values block lines: "icon | Title | Text"; keep the icon names (flame, leaf, clock) in English. */
    __('flame | Lit by hand | Every candle and lamp is lit at dusk by the front-of-house team.
leaf | Coast & garden | Fish from boats we know by name; vegetables from two walled gardens.
clock | Nothing rushed | Two seatings a night, so your table is yours for the evening.', 'cobbleandcandle');
};
