// Writes resources/lang/block-strings.php: every user-facing string default from
// plugins/cobbleandcandle-core/blocks/*/block.json wrapped in __() so `wp i18n make-pot` can extract it.
// At render time app/blocks.php swaps an untouched default for its translation.
// Run: npm run translate:blocks (also part of npm run translate).
import { readFileSync, writeFileSync, readdirSync } from 'node:fs'

// Attribute keys that hold identifiers, not copy.
const SKIP = new Set(['boardMenu', 'art', 'seatings'])
const php = (s) => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`

const lines = []
for (const dir of readdirSync('plugins/cobbleandcandle-core/blocks').sort()) {
  const meta = JSON.parse(readFileSync(`plugins/cobbleandcandle-core/blocks/${dir}/block.json`, 'utf8'))
  for (const [key, schema] of Object.entries(meta.attributes || {})) {
    const value = schema.default
    if (typeof value !== 'string' || value === '' || value.startsWith('/') || SKIP.has(key)) continue
    const note = key === 'items' && dir === 'values' ? 'Values block lines: "icon | Title | Text"; keep the icon names (flame, leaf, clock) in English.' : `Default for the ${meta.title} block setting "${key}".`
    lines.push(`\t/* translators: ${note} */`, `\t__( ${php(value)}, 'cobbleandcandle' );`)
  }
}

writeFileSync('resources/lang/block-strings.php', `<?php
/**
 * Generated by scripts/block-strings.mjs. Do not edit: run \`npm run translate:blocks\`.
 * Block setting defaults, listed so translation tools can find them. Never loaded at runtime.
 *
 * @package Cobble_And_Candle
 */

// phpcs:disable -- generated extraction list.
return static function () {
${lines.join('\n')}
};
`)
console.log(`resources/lang/block-strings.php: ${lines.length / 2} strings`)
