# -*- coding: utf-8 -*-
"""Demo content for the three themes. Every theme has the SAME shape (list lengths match)
so one set of templates/components renders all three. In WordPress this becomes real
CMS content (CPTs / ACF / options) -- the per-theme copy here only exists for the demo switcher."""

DAYS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
X = None  # closed

THEMES = {}

# ---------------------------------------------------------------- LAMPWRIGHT
THEMES["lampwright"] = dict(
  label="Lampwright", style="Candlelit Old Town",
  brand="Lampwright", sub="Dining Rooms · est. 1888", est="1888", mono="L", sign1="L", sign2="EST · 1888",
  kicker="Supper by candlelight · Since 1888",
  h1="Supper by <em>candlelight</em> on the old cobbles.",
  lede="A seasonal tasting menu served in three restored merchant houses, each lit as it was a century ago. Two seatings nightly.",
  reserve="Reserve a table", reserve_short="Reserve", menu_btn="View the menu", order="Order online",
  caption="Chandler’s Wharf at dusk",
  strip_tonight="Tonight’s seatings · 6:00 & 8:30",
  sig=dict(title="Signatures of the house", intro="Three plates that have stayed on the menu through every season, because guests would riot otherwise.",
    dishes=[
      dict(name="Hand-dived scallop", desc="Brown butter, cider, smoked hazelnut", price="$34", badges=["GF"], flag="Chef’s pick", art="plate"),
      dict(name="Dry-aged duck, two ways", desc="Cherry jus, celeriac, black garlic", price="$58", badges=[], flag="", art="duck"),
      dict(name="Burnt honey custard", desc="Bee pollen, shortbread, candied lemon", price="$16", badges=["V"], flag="", art="dessert"),
    ]),
  menu_title="From the bill of fare", menu_intro="Our menus are written each morning and printed on the press in the cellar.",
  menu=[
    dict(name="Tasting", intro="Seven courses · $125 · wine pairing $85", cats=[
      dict(name="To begin", items=[
        dict(name="Oyster, cucumber & dill", desc="Chandler’s Bay oyster, buttermilk, caviar", price="$9", badges=["GF"], flag=""),
        dict(name="Ember-roasted beetroot", desc="Aged goat’s curd, rye crumb, dill oil", price="$22", badges=["V"], flag=""),
        dict(name="Hand-dived scallop", desc="Brown butter, cider, smoked hazelnut", price="$34", badges=["GF"], flag="Chef’s pick"),
        dict(name="Chicken liver parfait", desc="Madeira jelly, toasted brioche", price="$19", badges=[], flag=""),
      ]),
      dict(name="Main courses", items=[
        dict(name="Dry-aged duck, two ways", desc="Cherry jus, celeriac, black garlic", price="$58", badges=[], flag="Popular"),
        dict(name="Turbot on the bone", desc="Mussels, champagne, sea vegetables", price="$54", badges=["GF"], flag=""),
        dict(name="Wild mushroom pithivier", desc="Truffle, Madeira, pickled walnut", price="$38", badges=["V"], flag=""),
        dict(name="Venison loin, juniper", desc="Smoked chilli, pear, chard", price="$52", badges=["GF", "S"], flag=""),
      ]),
      dict(name="On the side", items=[
        dict(name="Buttered heritage carrots", desc="Honey, thyme", price="$9", badges=["V", "GF"], flag=""),
        dict(name="Duck-fat potatoes", desc="Rosemary salt", price="$9", badges=["GF"], flag=""),
        dict(name="Leaves from the walled garden", desc="Mustard dressing", price="$8", badges=["VG", "GF"], flag=""),
        dict(name="Sourdough & cultured butter", desc="Baked in the house oven", price="$6", badges=["V"], flag=""),
      ]),
      dict(name="Sweets", items=[
        dict(name="Burnt honey custard", desc="Bee pollen, shortbread, candied lemon", price="$16", badges=["V"], flag="Chef’s pick"),
        dict(name="Dark chocolate & stout", desc="Malt ice cream, cocoa nib", price="$15", badges=["V"], flag=""),
        dict(name="Poached quince", desc="Spiced syrup, oat crumble", price="$14", badges=["VG"], flag=""),
        dict(name="British cheeses", desc="Quince paste, oatcakes, celery", price="$18", badges=["V"], flag=""),
      ]),
    ]),
    dict(name="À la carte", intro="Served in the front parlour from 5:30pm", cats=[
      dict(name="Small plates", items=[
        dict(name="Smoked eel croquettes", desc="Horseradish cream", price="$14", badges=[], flag=""),
        dict(name="Devilled hen’s eggs", desc="Cayenne, cress", price="$9", badges=["V", "GF", "S"], flag=""),
        dict(name="Potted shrimp", desc="Mace butter, toast", price="$16", badges=[], flag="Popular"),
        dict(name="Charred leeks", desc="Hazelnut romesco", price="$12", badges=["VG", "GF"], flag=""),
      ]),
      dict(name="Larger plates", items=[
        dict(name="Lamp-roasted chicken", desc="Bread sauce, roast juices · for two", price="$68", badges=[], flag=""),
        dict(name="Market fish", desc="Brown shrimp, capers, sorrel", price="$36", badges=["GF"], flag=""),
        dict(name="Barley risotto", desc="Squash, sage, aged cheddar", price=None, variants=[["Starter", "$18"], ["Main", "$29"]], badges=["V"], flag=""),
        dict(name="Rib of beef", desc="Bone marrow, watercress · 32oz", price="$110", badges=["GF"], flag=""),
      ]),
    ]),
    dict(name="Cellar", intro="1,400 bins · ask for the sommelier’s ledger", cats=[
      dict(name="By the glass", items=[
        dict(name="Côte de Beaune, 2019", desc="Burgundy · red cherry, forest floor", price=None, variants=[["Glass", "$24"], ["Bottle", "$96"]], badges=["VG"], flag="Sommelier’s pick"),
        dict(name="Rioja Gran Reserva, 2015", desc="Spain · leather, dried plum", price=None, variants=[["Glass", "$19"], ["Bottle", "$76"]], badges=["VG"], flag=""),
        dict(name="Chablis 1er Cru, 2021", desc="Burgundy · oyster shell, lemon", price=None, variants=[["Glass", "$21"], ["Bottle", "$84"]], badges=["VG"], flag=""),
        dict(name="English sparkling, Brut", desc="Sussex · brioche, green apple", price=None, variants=[["Glass", "$17"], ["Bottle", "$72"]], badges=["VG"], flag=""),
      ]),
      dict(name="Fortified & after dinner", items=[
        dict(name="Vintage port, 20-year tawny", desc="Served with Stilton & oatcakes", price=None, variants=[["Glass", "$18"], ["Bottle", "$140"]], badges=["V"], flag=""),
        dict(name="Malmsey Madeira, 10-year", desc="Burnt sugar, walnut", price=None, variants=[["Glass", "$16"], ["Bottle", "$110"]], badges=["VG"], flag=""),
        dict(name="Lampwright Old Fashioned", desc="Rye, burnt honey, orange", price="$17", badges=["VG"], flag="House cocktail"),
        dict(name="Calvados, Pays d’Auge", desc="15-year · baked apple", price=None, variants=[["25ml", "$15"], ["50ml", "$28"]], badges=["VG"], flag=""),
      ]),
    ]),
    dict(name="Sweets", intro="Served until 10:30pm", cats=[
      dict(name="Puddings & cheese", items=[
        dict(name="Burnt honey custard", desc="Bee pollen, shortbread", price="$16", badges=["V"], flag="Chef’s pick"),
        dict(name="Dark chocolate & stout", desc="Malt ice cream, cocoa nib", price="$15", badges=["V"], flag=""),
        dict(name="Poached quince", desc="Spiced syrup, oat crumble", price="$14", badges=["VG", "GF"], flag=""),
        dict(name="British cheeses", desc="Three, five or seven", price=None, variants=[["3", "$14"], ["5", "$20"], ["7", "$26"]], badges=["V"], flag=""),
      ]),
    ]),
  ],
  board=dict(title="Tonight’s Cellar", sub="By the glass", lines=[["Côte de Beaune ’19", "$24"], ["Rioja Gran Reserva ’15", "$19"], ["Malmsey Madeira, 10-yr", "$16"]], foot="Ask your sommelier"),
  story=dict(kicker="Our story", title="A lamplighter’s house, still lit by hand",
    p1="In 1888 the Wharf’s lamplighter turned his front parlour into a supper room for sailors coming off the evening tide. The brass lamps he polished every dusk still hang above table four.",
    p2="Today Chef Margot Ellery cooks from the same coast and the same walled gardens, with a kitchen that runs on wood, patience and a very old copper stockpot.",
    chef="Margot Ellery", role="Chef-patron since 2014",
    quote="We cook the way the house is lit: slowly, warmly, and with nothing to hide.",
    timeline=[["1888", "The first supper", "Lamplighter Josiah Wren opens his parlour to the evening tide."],
              ["1931", "The cellar opens", "The old coal store becomes a wine cellar of 400 bins."],
              ["1998", "Cathedral Close", "A second house opens in a former vestry beside the cathedral."],
              ["2014", "Chef Margot", "Margot Ellery takes the pass and rewrites the bill of fare."]],
    values=[["Lit by hand", "Every candle and lamp is lit at dusk by the front-of-house team."],
            ["Coast & garden", "Fish from boats we know by name; vegetables from two walled gardens."],
            ["Nothing rushed", "Two seatings a night, so your table is yours for the evening."]]),
  events=[
    dict(title="Candlelit Cellar Supper", type="Tasting", day="15", mon="Oct", wd="Thu", time="7:00 pm", loc=0, price="$145 pp", status="12 seats left", blurb="Six courses in the vaulted cellar, paired with rare Burgundy from the ledger."),
    dict(title="Harvest Moon Dinner", type="Seasonal", day="24", mon="Oct", wd="Sat", time="6:30 pm", loc=1, price="$120 pp", status="Booking now", blurb="A long-table feast of game, orchard fruit and cider under the cathedral windows."),
    dict(title="String quartet in the parlour", type="Live music", day="31", mon="Oct", wd="Sat", time="8:00 pm", loc=0, price="No cover", status="Walk-ins welcome", blurb="Hallowe’en by lamplight with Schubert, Dvořák and a smoked-pumpkin menu."),
    dict(title="Christmas Eve by Lamplight", type="Holiday", day="24", mon="Dec", wd="Thu", time="5:00 pm", loc=2, price="$165 pp", status="Waitlist", blurb="Our most-requested night: goose, mulled claret and carols on the Mint steps."),
  ],
  ev_long=["Once a season we carry the candelabra down into the cellar and set a single table of twenty-two between the racks. Chef Margot cooks six courses around a handful of bottles our sommelier has been saving.",
           "Expect hand-written place cards, a short talk from the cellar master and a nightcap of 20-year tawny by the old coal chute. Smart dress; the cellar stays at 14°C, so bring a layer."],
  ev_menu=["Oyster, cucumber & dill", "Scallop, brown butter, hazelnut", "Turbot on the bone, champagne", "Venison loin, juniper, pear", "Burnt honey custard"],
  reviews=[
    dict(q="The kind of room that makes you lower your voice and order another bottle. Every plate glowed.", who="The Old Town Courier", src="★★★★★ · Restaurant of the Year 2025"),
    dict(q="Ellery’s duck is reason enough to cross the harbour. The candlelight is just the bonus.", who="Harbour & Hearth Magazine", src="Critic’s choice"),
    dict(q="We celebrated our 30th anniversary in the cellar. Faultless, unhurried, unforgettable.", who="Eleanor W., guest", src="★★★★★ · Google review"),
  ],
  private=dict(title="Private dining in the Lamp Room", text="Up to 28 guests by candlelight, with a dedicated sommelier and a menu written for the occasion.",
    rooms=[["The Lamp Room", "Seats 28"], ["The Cellar Table", "Seats 22"], ["The Snug", "Seats 10"]]),
  news=dict(title="Letters from the Wharf", text="A short, monthly note on new menus, cellar finds and seasonal suppers."),
  nf=dict(title="This lane is unlit.", text="The page you were after has slipped down a side street. Let us light the way back."),
  gal_title="Inside the houses",
  locs=[
    dict(name="Chandler’s Wharf", street="7 Chandler’s Wharf", area="Old Harbour", phone="(555) 014-1888", email="wharf@lampwright.demo",
      hours=[X, X, ["17:30", "23:00"], ["17:30", "23:00"], ["17:30", "23:00"], ["17:30", "23:00"], ["17:00", "22:00"]],
      holiday=[["Thu 26 Nov", "Thanksgiving", "1:00 – 8:00 pm"], ["Thu 24 Dec", "Christmas Eve", "5:00 – 11:00 pm"], ["Fri 25 Dec", "Christmas Day", "Closed"]],
      parking="Harbour Street garage (2 min walk), validated after 6pm. Cobbled lane, no drop-off at the door.",
      transit="Harbour ferry stop, 3 min. Tram 4 to Customs Steps.", access="Step-free entrance via Ropewalk Lane; accessible restroom on ground floor.",
      booking="native", provider=""),
    dict(name="Cathedral Close", street="2 Vestry Row", area="Cathedral Close", phone="(555) 014-1898", email="close@lampwright.demo",
      hours=[X, ["17:00", "22:00"], ["17:00", "22:00"], ["17:00", "22:00"], ["17:00", "23:00"], ["17:00", "23:00"], ["12:00", "21:00"]],
      holiday=[["Thu 26 Nov", "Thanksgiving", "Closed"], ["Thu 24 Dec", "Christmas Eve", "4:00 – 10:00 pm"], ["Fri 25 Dec", "Christmas Day", "Closed"]],
      parking="Pay-and-display on Deanery Street. No parking inside the Close.", transit="Bus 12 and 19 to Cathedral Gate.",
      access="Two steps at the entrance; portable ramp on request.", booking="opentable", provider="OpenTable"),
    dict(name="Old Mint Quarter", street="41 Coiners’ Yard", area="Old Mint Quarter", phone="(555) 014-1902", email="mint@lampwright.demo",
      hours=[X, X, X, X, ["17:30", "23:30"], ["17:30", "23:30"], ["17:00", "22:00"]],
      holiday=[["Thu 26 Nov", "Thanksgiving", "Closed"], ["Thu 24 Dec", "Christmas Eve", "5:00 – 11:00 pm"], ["Fri 25 Dec", "Christmas Day", "Closed"]],
      parking="Mint Yard car park, evenings $6 flat.", transit="Tram 2 to Mint Square.", access="Fully step-free; lift to the mezzanine.",
      booking="call", provider=""),
  ],
)

# ---------------------------------------------------------------- EMBER & ARCH
THEMES["ember-arch"] = dict(
  label="The Ember & Arch", style="Brick & Ember",
  brand="The Ember & Arch", sub="Tavern & Hearth · est. 1902", est="1902", mono="E&amp;A", sign1="E&amp;A", sign2="EST · 1902",
  kicker="Hearth, ale & roasts · Since 1902",
  h1="Pull up a stool by the <em>hearth</em>.",
  lede="Wood-fired roasts, cask ales and long tables in three old brick taverns along the canal quarter. Walk-ins welcome; book for six or more.",
  reserve="Book a table", reserve_short="Book", menu_btn="View menu", order="Order pickup",
  caption="Brickmakers’ Row on a Friday night",
  strip_tonight="Quiz night Tues · Roasts all Sunday",
  sig=dict(title="Off the hearth", intro="Everything below spends time over oak and apple wood in the open hearth that gave us our name.",
    dishes=[
      dict(name="Ember-roasted pork belly", desc="Crackling, cider apples, burnt onion jus", price="$29", badges=["GF"], flag="House favourite", art="plate"),
      dict(name="Wild mushroom & ale pie", desc="Suet crust, mash, stout gravy", price="$22", badges=["V"], flag="", art="pie"),
      dict(name="Sticky toffee pudding", desc="Toffee sauce, clotted cream", price="$11", badges=["V"], flag="", art="dessert"),
    ]),
  menu_title="Today at the tavern", menu_intro="Chalked up fresh at 4pm. Kitchen open till 10, bar till late.",
  menu=[
    dict(name="Hearth", intro="Cooked over oak in the open hearth", cats=[
      dict(name="Starters", items=[
        dict(name="Scotch egg, still warm", desc="Black pudding, brown sauce", price="$11", badges=[], flag="House favourite"),
        dict(name="Smoked mackerel pâté", desc="Pickled cucumber, toast", price="$12", badges=[], flag=""),
        dict(name="Ale-battered onion rings", desc="Malt vinegar salt, curry mayo", price="$9", badges=["V", "S"], flag=""),
        dict(name="Ember-roasted beets", desc="Whipped feta, hazelnut", price="$12", badges=["V", "GF"], flag=""),
      ]),
      dict(name="From the hearth", items=[
        dict(name="Ember-roasted pork belly", desc="Crackling, cider apples, burnt onion jus", price="$29", badges=["GF"], flag="House favourite"),
        dict(name="Half chicken, spit-roast", desc="Piri-piri butter, charred lemon", price="$26", badges=["GF", "S"], flag=""),
        dict(name="Hearth-baked cauliflower", desc="Romesco, crispy capers", price="$21", badges=["VG", "GF"], flag=""),
        dict(name="Ox cheek, slow embers", desc="Horseradish mash, red wine", price="$31", badges=["GF"], flag="Popular"),
      ]),
      dict(name="Pub classics", items=[
        dict(name="Fish & chips, beer-battered", desc="Mushy peas, tartare, malt vinegar", price="$24", badges=[], flag=""),
        dict(name="Wild mushroom & ale pie", desc="Suet crust, mash, stout gravy", price="$22", badges=["V"], flag=""),
        dict(name="The Arch burger", desc="Aged beef, smoked cheddar, pickles", price="$19", badges=[], flag=""),
        dict(name="Bangers & mash", desc="Cumberland sausage, onion gravy", price="$18", badges=[], flag=""),
      ]),
      dict(name="Puddings", items=[
        dict(name="Sticky toffee pudding", desc="Toffee sauce, clotted cream", price="$11", badges=["V"], flag="House favourite"),
        dict(name="Treacle tart", desc="Lemon, crème fraîche", price="$10", badges=["V"], flag=""),
        dict(name="Apple & blackberry crumble", desc="Custard or ice cream", price="$10", badges=["VG"], flag=""),
        dict(name="Cheese board", desc="Three local cheeses, chutney", price="$15", badges=["V"], flag=""),
      ]),
    ]),
    dict(name="Pub classics", intro="Served all day, every day", cats=[
      dict(name="Sharing", items=[
        dict(name="Ploughman’s board", desc="Ham hock, cheddar, pickles, bread", price="$24", badges=[], flag="For two"),
        dict(name="Pork scratchings", desc="Apple sauce", price="$5", badges=["GF"], flag=""),
        dict(name="Hot wings, ember glaze", desc="Blue cheese dip", price="$14", badges=["GF", "S"], flag=""),
        dict(name="Halloumi fries", desc="Hot honey, mint", price="$11", badges=["V", "GF"], flag=""),
      ]),
      dict(name="Sunday roasts", items=[
        dict(name="Roast sirloin", desc="Yorkshire pudding, all the trimmings", price="$28", badges=[], flag="Popular"),
        dict(name="Roast chicken", desc="Sage & onion stuffing, bread sauce", price="$24", badges=[], flag=""),
        dict(name="Nut roast", desc="Gravy, roast potatoes, greens", price="$20", badges=["VG"], flag=""),
        dict(name="Kids’ roast", desc="Smaller plate of any roast", price=None, variants=[["S", "$10"], ["M", "$14"]], badges=[], flag=""),
      ]),
    ]),
    dict(name="On tap", intro="Eight cask lines · two ciders · one stout", cats=[
      dict(name="Cask & keg", items=[
        dict(name="Kiln Yard Bitter, cask", desc="Brewed for us across the canal · 4.2%", price=None, variants=[["Half", "$5"], ["Pint", "$8"]], badges=["VG"], flag="House pour"),
        dict(name="Foundry Stout", desc="Roast coffee, cocoa · 4.8%", price=None, variants=[["Half", "$5"], ["Pint", "$9"]], badges=["VG"], flag=""),
        dict(name="Canal IPA", desc="Citrus, pine · 5.6%", price=None, variants=[["Half", "$6"], ["Pint", "$10"]], badges=["VG"], flag=""),
        dict(name="Orchard cider, still", desc="Somerset · 6.0%", price=None, variants=[["Half", "$5"], ["Pint", "$9"]], badges=["VG", "GF"], flag=""),
      ]),
      dict(name="Wine & spirits", items=[
        dict(name="House red, Côtes du Rhône", desc="Easy, peppery", price=None, variants=[["Glass", "$11"], ["Bottle", "$40"]], badges=["VG"], flag=""),
        dict(name="House white, Picpoul", desc="Crisp, salty", price=None, variants=[["Glass", "$11"], ["Bottle", "$40"]], badges=["VG"], flag=""),
        dict(name="Hot buttered rum", desc="Spiced, by the fire", price="$13", badges=["V"], flag="Winter only"),
        dict(name="Single malt flight", desc="Three drams, chosen by the bar", price="$24", badges=["VG"], flag=""),
      ]),
    ]),
    dict(name="Puddings", intro="Big enough to share (we won’t judge)", cats=[
      dict(name="Puddings", items=[
        dict(name="Sticky toffee pudding", desc="Toffee sauce, clotted cream", price="$11", badges=["V"], flag="House favourite"),
        dict(name="Treacle tart", desc="Lemon, crème fraîche", price="$10", badges=["V"], flag=""),
        dict(name="Apple & blackberry crumble", desc="Custard or oat ice cream", price="$10", badges=["VG"], flag=""),
        dict(name="Ice cream", desc="Vanilla, chocolate, salted caramel", price=None, variants=[["1 scoop", "$4"], ["3 scoops", "$9"]], badges=["V", "GF"], flag=""),
      ]),
    ]),
  ],
  board=dict(title="On the Board", sub="Today’s specials", lines=[["Venison stew, dumplings", "$26"], ["Smoked haddock rarebit", "$17"], ["Sticky toffee pudding", "$11"]], foot="Chalked up daily at 4pm"),
  story=dict(kicker="Our story", title="A brickmakers’ tavern since the kilns burned",
    p1="The Ember & Arch opened in 1902 to pour ale for the men who fired the canal kilns. The arch over the bar is made from their bricks, and the hearth has been lit almost every night since.",
    p2="Head chef Tomás Brennan cooks over oak and apple wood in that same hearth, with a menu of proper pub food done carefully and priced fairly.",
    chef="Tomás Brennan", role="Head chef & hearth-keeper",
    quote="A good pub feeds the whole street. We just happen to do it with fire.",
    timeline=[["1902", "First pints poured", "The kiln workers’ tavern opens at Brickmakers’ Row."],
              ["1948", "The arch is built", "Salvaged kiln bricks form the great arch over the bar."],
              ["2009", "Foundry Lane", "A second tavern opens in the old iron foundry."],
              ["2019", "Kiln Yard", "Our third house opens with a brewery next door."]],
    values=[["Fire first", "Every hearth dish is cooked over oak and apple wood."],
            ["Local pours", "Cask ale from three brewers within a mile of the canal."],
            ["Everyone welcome", "Dogs, kids, walkers and wedding parties all fit."]]),
  events=[
    dict(title="Tuesday Pub Quiz", type="Quiz", day="13", mon="Oct", wd="Tue", time="8:00 pm", loc=0, price="$3 pp", status="Teams of 6", blurb="Six rounds, one picture round, a pint for the winners and a wooden spoon for last."),
    dict(title="Oktoberfest on the Canal", type="Seasonal", day="17", mon="Oct", wd="Sat", time="12:00 pm", loc=1, price="Free entry", status="Booking advised", blurb="Steins, brass band, pretzels and pork knuckle from the hearth all afternoon."),
    dict(title="Folk Night by the Fire", type="Live music", day="23", mon="Oct", wd="Fri", time="8:30 pm", loc=2, price="No cover", status="Walk-ins welcome", blurb="Fiddles, squeezeboxes and a session anyone can join. Bring an instrument."),
    dict(title="Bonfire Night Roast", type="Holiday", day="5", mon="Nov", wd="Thu", time="6:00 pm", loc=0, price="$45 pp", status="Booking now", blurb="Hog roast in the yard, sparklers, mulled cider and the canal fireworks."),
  ],
  ev_long=["Every Tuesday since 1987, Brickmakers’ Row has gone quiet at 8pm for the quiz. Six rounds from our quizmaster Dot, one picture round and a music round that always starts arguments.",
           "Teams of up to six, $3 a head with every penny to the canal trust. Winners take a round of pints; last place takes the wooden spoon home for the week."],
  ev_menu=["Scotch egg, still warm", "Ale-battered onion rings", "Hot wings, ember glaze", "The Arch burger", "Sticky toffee pudding"],
  reviews=[
    dict(q="The best Sunday roast in the canal quarter, and the Yorkshire puddings are the size of hats.", who="The Old Town Courier", src="★★★★★ · Pub of the Year 2025"),
    dict(q="Brennan treats the hearth like an instrument. The pork belly sings.", who="Harbour & Hearth Magazine", src="Critic’s choice"),
    dict(q="Came in out of the rain, stayed four hours. The kind of pub you wish was on your street.", who="Sam & Priya, guests", src="★★★★★ · Google review"),
  ],
  private=dict(title="Book the Snug or the whole Yard", text="Birthdays, wakes, rehearsal dinners and work dos for 10 to 120, with a hog roast if you like.",
    rooms=[["The Kiln Room", "Seats 40"], ["The Snug", "Seats 12"], ["The Yard", "Stands 120"]]),
  news=dict(title="The Tavern Bulletin", text="New guest ales, quiz results and event tickets before they sell out."),
  nf=dict(title="Last orders on this page.", text="Whatever you were looking for has wandered off down the canal. Here’s the way back to the bar."),
  gal_title="Round the taverns",
  locs=[
    dict(name="Brickmakers’ Row", street="3 Brickmakers’ Row", area="Canal Quarter", phone="(555) 017-1902", email="row@emberandarch.demo",
      hours=[["12:00", "23:00"], ["12:00", "23:00"], ["12:00", "23:00"], ["12:00", "23:00"], ["12:00", "25:00"], ["12:00", "25:00"], ["12:00", "22:00"]],
      holiday=[["Thu 26 Nov", "Thanksgiving", "12:00 – 6:00 pm"], ["Thu 24 Dec", "Christmas Eve", "12:00 – 11:00 pm"], ["Fri 25 Dec", "Christmas Day", "12:00 – 3:00 pm"]],
      parking="Canal Basin car park, 4 min walk. Bike racks by the arch.", transit="Bus 7 to Kiln Bridge. Water taxi to Basin Steps.",
      access="Step-free main bar; accessible restroom.", booking="native", provider=""),
    dict(name="Foundry Lane", street="18 Foundry Lane", area="Ironworks", phone="(555) 017-1909", email="foundry@emberandarch.demo",
      hours=[["11:00", "24:00"]] * 7,
      holiday=[["Thu 26 Nov", "Thanksgiving", "11:00 am – 8:00 pm"], ["Thu 24 Dec", "Christmas Eve", "11:00 am – midnight"], ["Fri 25 Dec", "Christmas Day", "Closed"]],
      parking="Street parking after 6pm; Foundry car park 2 min.", transit="Tram 3 to Ironworks.", access="Step-free; hearing loop at the bar.",
      booking="resy", provider="Resy"),
    dict(name="Kiln Yard", street="1 Kiln Yard", area="Kiln Yard", phone="(555) 017-1919", email="kiln@emberandarch.demo",
      hours=[["16:00", "22:00"], ["16:00", "22:00"], ["16:00", "22:00"], ["16:00", "22:00"], ["12:00", "24:00"], ["12:00", "24:00"], ["12:00", "21:00"]],
      holiday=[["Thu 26 Nov", "Thanksgiving", "Closed"], ["Thu 24 Dec", "Christmas Eve", "12:00 – 10:00 pm"], ["Fri 25 Dec", "Christmas Day", "Closed"]],
      parking="Brewery yard parking, free for guests.", transit="Bus 7 to Kiln Yard.", access="Cobbled yard; level entrance via brewery gate.",
      booking="call", provider=""),
  ],
)

# ---------------------------------------------------------------- ASHLAR & IRON
THEMES["ashlar-iron"] = dict(
  label="Ashlar & Iron", style="Limestone & Iron",
  brand="Ashlar &amp; Iron", sub="Dining Room & Wine Bar · est. 1874", est="1874", mono="A&amp;I", sign1="A&amp;I", sign2="EST · 1874",
  kicker="Old Customs Quarter · Since 1874",
  h1="Long lunches under <em>limestone</em> arches.",
  lede="Regional cooking and a deep wine list in three restored stone buildings. Sunlit at noon, candlelit after dark.",
  reserve="Reserve", reserve_short="Reserve", menu_btn="See the menu", order="Order to collect",
  caption="The Old Customs House, west door",
  strip_tonight="Lunch from 11:30 · Dinner from 6:00",
  sig=dict(title="Plates of the season", intro="Regional cooking built around the market, the wood oven and a cellar of quiet, characterful wines.",
    dishes=[
      dict(name="Slow-braised lamb shoulder", desc="White beans, rosemary, salsa verde", price="$36", badges=["GF"], flag="Chef’s pick", art="plate"),
      dict(name="Heritage tomato tart", desc="Whipped ricotta, basil, aged balsamic", price="$18", badges=["V"], flag="", art="pie"),
      dict(name="Cheese from the cave", desc="Three regional cheeses, honey, walnut bread", price="$19", badges=["V"], flag="", art="board"),
    ]),
  menu_title="Today’s menus", menu_intro="Lunch and dinner are written around the morning market and change a little every day.",
  menu=[
    dict(name="Lunch", intro="Two courses $34 · three courses $42", cats=[
      dict(name="To start", items=[
        dict(name="Heritage tomato tart", desc="Whipped ricotta, basil, aged balsamic", price="$18", badges=["V"], flag="Chef’s pick"),
        dict(name="Burrata & blood orange", desc="Fennel, pistachio", price="$17", badges=["V", "GF"], flag=""),
        dict(name="Fish soup", desc="Rouille, gruyère, croutons", price="$16", badges=[], flag=""),
        dict(name="Grilled peppers", desc="Anchovy, caper, chilli", price="$14", badges=["GF", "S"], flag=""),
      ]),
      dict(name="Mains", items=[
        dict(name="Slow-braised lamb shoulder", desc="White beans, rosemary, salsa verde", price="$36", badges=["GF"], flag="Popular"),
        dict(name="Day-boat hake", desc="Mussels, saffron, sea herbs", price="$34", badges=["GF"], flag=""),
        dict(name="Wood-oven chicken", desc="Lemon, garlic, fries", price="$29", badges=["GF"], flag=""),
        dict(name="Chickpea & chard stew", desc="Harissa, flatbread", price="$22", badges=["VG", "S"], flag=""),
      ]),
      dict(name="Sides", items=[
        dict(name="Crushed potatoes", desc="Olive oil, sea salt", price="$8", badges=["VG", "GF"], flag=""),
        dict(name="Bitter leaves", desc="Mustard dressing", price="$8", badges=["VG", "GF"], flag=""),
        dict(name="Green beans", desc="Shallot, almond", price="$9", badges=["VG", "GF"], flag=""),
        dict(name="Bread & olive oil", desc="Baked in the wood oven", price="$6", badges=["VG"], flag=""),
      ]),
      dict(name="Desserts", items=[
        dict(name="Poached pear", desc="Vanilla anglaise, almond", price="$12", badges=["V", "GF"], flag=""),
        dict(name="Olive-oil cake", desc="Orange, crème fraîche", price="$11", badges=["V"], flag="Chef’s pick"),
        dict(name="Dark chocolate pot", desc="Sea salt, shortbread", price="$12", badges=["V"], flag=""),
        dict(name="Cheese from the cave", desc="Honey, walnut bread", price="$19", badges=["V"], flag=""),
      ]),
    ]),
    dict(name="Dinner", intro="From 6pm · candlelit", cats=[
      dict(name="To start", items=[
        dict(name="Beef tartare", desc="Smoked egg yolk, sourdough", price="$19", badges=[], flag=""),
        dict(name="Scallops, brown butter", desc="Cauliflower, capers", price="$24", badges=["GF"], flag="Popular"),
        dict(name="Charred leeks", desc="Romesco, hazelnut", price="$15", badges=["VG", "GF"], flag=""),
        dict(name="Duck liver parfait", desc="Fig chutney, brioche", price="$18", badges=[], flag=""),
      ]),
      dict(name="Mains", items=[
        dict(name="Côte de boeuf, for two", desc="Béarnaise, fries, leaves", price="$98", badges=["GF"], flag=""),
        dict(name="Rabbit pappardelle", desc="Mustard, tarragon, pancetta", price="$28", badges=[], flag=""),
        dict(name="Turbot, beurre blanc", desc="Samphire, new potatoes", price="$46", badges=["GF"], flag=""),
        dict(name="Risotto of squash", desc="Sage, aged pecorino", price=None, variants=[["Starter", "$16"], ["Main", "$26"]], badges=["V", "GF"], flag=""),
      ]),
    ]),
    dict(name="Wine list", intro="380 bins · 30 by the glass · carafes of everything", cats=[
      dict(name="Red", items=[
        dict(name="Cabernet Franc, Chinon 2021", desc="Loire Valley · served cellar-cool", price=None, variants=[["Glass", "$15"], ["Carafe", "$38"], ["Bottle", "$58"]], badges=["VG"], flag="Sommelier’s pick"),
        dict(name="Grenache, Priorat 2019", desc="Catalonia · slate, black fruit", price=None, variants=[["Glass", "$18"], ["Carafe", "$46"], ["Bottle", "$72"]], badges=["VG"], flag=""),
        dict(name="Nebbiolo, Langhe 2020", desc="Piedmont · rose, tar", price=None, variants=[["Glass", "$17"], ["Carafe", "$44"], ["Bottle", "$68"]], badges=["VG"], flag=""),
        dict(name="Pinot Noir, Jura 2022", desc="Light, crunchy red fruit", price=None, variants=[["Glass", "$16"], ["Carafe", "$40"], ["Bottle", "$62"]], badges=["VG"], flag=""),
      ]),
      dict(name="White & sparkling", items=[
        dict(name="Chenin Blanc, Vouvray 2022", desc="Loire · quince, honey", price=None, variants=[["Glass", "$14"], ["Carafe", "$36"], ["Bottle", "$54"]], badges=["VG"], flag=""),
        dict(name="Albariño, Rías Baixas 2023", desc="Galicia · saline, peach", price=None, variants=[["Glass", "$13"], ["Carafe", "$34"], ["Bottle", "$50"]], badges=["VG"], flag=""),
        dict(name="Crémant de Bourgogne", desc="Brioche, green apple", price=None, variants=[["Glass", "$14"], ["Bottle", "$56"]], badges=["VG"], flag=""),
        dict(name="Vermouth spritz", desc="House vermouth, soda, olive", price="$12", badges=["VG"], flag="Aperitivo"),
      ]),
    ]),
    dict(name="Cheese", intro="From the cave beneath the Customs House", cats=[
      dict(name="Cheese from the cave", items=[
        dict(name="Comté, 24 months", desc="Nutty, crystalline", price="$9", badges=["V", "GF"], flag=""),
        dict(name="Tomme de chèvre", desc="Goat, grassy, lemony", price="$9", badges=["V", "GF"], flag=""),
        dict(name="Fourme d’Ambert", desc="Mild blue, honey", price="$9", badges=["V", "GF"], flag="Chef’s pick"),
        dict(name="Selection", desc="With walnut bread & quince", price=None, variants=[["3", "$19"], ["5", "$29"]], badges=["V"], flag=""),
      ]),
    ]),
  ],
  board=dict(title="Market Slate", sub="Today’s plates", lines=[["Asparagus, brown butter", "$16"], ["Rabbit pappardelle", "$28"], ["Poached pear, anglaise", "$12"]], foot="Changes with the market"),
  story=dict(kicker="Our story", title="Honeyed stone, iron lanterns, an open door",
    p1="The Old Customs House was finished in 1874 from the same honey-coloured limestone as the quay. For a century it weighed cargo; since 1996 it has weighed nothing heavier than a long lunch.",
    p2="Chef Inès Calder cooks the food of the river valleys around us, from a wood oven, a market list and a cellar of characterful growers.",
    chef="Inès Calder", role="Executive chef since 2017",
    quote="Stone keeps the warmth of the day. We try to cook like that, generously and with patience.",
    timeline=[["1874", "The Customs House", "Masons finish the limestone hall on the west quay."],
              ["1996", "A dining room", "The weighing hall reopens as a restaurant and wine bar."],
              ["2011", "Lantern Steps", "A second house opens in a former chandlery."],
              ["2017", "Chef Inès", "Inès Calder brings the wood oven and the market slate."]],
    values=[["Market first", "The slate is written after the morning market, never before."],
            ["Growers, not labels", "Wines from small families who farm what they bottle."],
            ["Day into night", "Bright for a long lunch; candlelit and quieter after dark."]]),
  events=[
    dict(title="Growers’ Dinner: Loire Valley", type="Tasting", day="16", mon="Oct", wd="Fri", time="7:00 pm", loc=0, price="$110 pp", status="14 seats left", blurb="Five courses with the Breton family of Chinon, who are bringing bottles from their own cellar."),
    dict(title="Truffle Market Lunch", type="Seasonal", day="25", mon="Oct", wd="Sun", time="12:30 pm", loc=1, price="$85 pp", status="Booking now", blurb="Autumn truffles shaved at the table over a four-course long lunch on the terrace."),
    dict(title="Jazz under the Arches", type="Live music", day="30", mon="Oct", wd="Fri", time="8:00 pm", loc=0, price="No cover", status="Walk-ins welcome", blurb="A trio in the old weighing hall with small plates and natural wine by the glass."),
    dict(title="New Year’s Eve at Cooper’s Gate", type="Holiday", day="31", mon="Dec", wd="Thu", time="7:30 pm", loc=2, price="$175 pp", status="Waitlist", blurb="Seven courses, champagne at midnight and the fireworks over the river from the gate."),
  ],
  ev_long=["Twice a year we invite a grower to cook alongside us. This autumn it’s the Breton family from Chinon, bringing five wines from their cellar, including two vintages that never left the domaine.",
           "Chef Inès writes a five-course menu around their Cabernet Franc and Chenin Blanc. Seating is at one long table in the weighing hall; the family speak between courses."],
  ev_menu=["Gougères & Crémant", "Pike quenelle, beurre blanc", "Rillons, lentils, Chinon jus", "Sainte-Maure de Touraine", "Tarte Tatin, crème fraîche"],
  reviews=[
    dict(q="A lunch that stretched into evening without anyone noticing. The wine list alone deserves a visit.", who="The Old Town Courier", src="★★★★★ · Best Wine List 2025"),
    dict(q="Calder’s lamb shoulder is a quiet masterpiece; the room, all honey stone and iron, does the rest.", who="Harbour & Hearth Magazine", src="Critic’s choice"),
    dict(q="Sunlight through the arches, a carafe of Chinon and that tomato tart. Perfect Sunday.", who="Marta L., guest", src="★★★★★ · Google review"),
  ],
  private=dict(title="Private dining in the Weighing Hall", text="From an intimate cellar table of eight to a long-table wedding lunch for ninety, beneath the original stone arches.",
    rooms=[["The Weighing Hall", "Seats 90"], ["The Cave Table", "Seats 8"], ["The Terrace", "Seats 36"]]),
  news=dict(title="The Quay Letter", text="Seasonal menus, growers’ dinners and new arrivals in the cellar, once a month."),
  nf=dict(title="This door is bricked up.", text="The page you’re after isn’t here anymore. Step back through the arch and we’ll find you a table."),
  gal_title="Stone, light & the table",
  locs=[
    dict(name="Old Customs House", street="12 Old Customs House Lane", area="West Quay", phone="(555) 012-1874", email="customs@ashlariron.demo",
      hours=[X, ["11:30", "22:30"], ["11:30", "22:30"], ["11:30", "22:30"], ["11:30", "22:30"], ["11:30", "22:30"], ["11:00", "16:00"]],
      holiday=[["Thu 26 Nov", "Thanksgiving", "12:00 – 7:00 pm"], ["Thu 24 Dec", "Christmas Eve", "11:30 am – 9:00 pm"], ["Fri 25 Dec", "Christmas Day", "Closed"]],
      parking="Quay car park (3 min), $2/hr. Valet Fri–Sat from 6pm.", transit="River bus to West Quay. Tram 1 to Customs Square.",
      access="Step-free via the north door; accessible restroom.", booking="native", provider=""),
    dict(name="Lantern Steps", street="4 Lantern Steps", area="Chandlery Quarter", phone="(555) 012-1911", email="steps@ashlariron.demo",
      hours=[["17:00", "23:00"], ["12:00", "23:00"], ["12:00", "23:00"], ["12:00", "23:00"], ["12:00", "23:00"], ["12:00", "23:00"], ["12:00", "23:00"]],
      holiday=[["Thu 26 Nov", "Thanksgiving", "5:00 – 10:00 pm"], ["Thu 24 Dec", "Christmas Eve", "12:00 – 9:00 pm"], ["Fri 25 Dec", "Christmas Day", "Closed"]],
      parking="No parking on the Steps; Chandlery garage 4 min.", transit="Tram 1 to Lantern Steps.", access="Upper room by stairs only; ground-floor dining is step-free.",
      booking="resy", provider="Resy"),
    dict(name="Cooper’s Gate", street="9 Cooper’s Gate", area="Old Walls", phone="(555) 012-1923", email="gate@ashlariron.demo",
      hours=[X, X, X, X, ["11:30", "22:00"], ["11:30", "22:00"], ["11:00", "16:00"]],
      holiday=[["Thu 26 Nov", "Thanksgiving", "Closed"], ["Thu 24 Dec", "Christmas Eve", "Closed"], ["Thu 31 Dec", "New Year’s Eve", "7:30 pm – 1:00 am"]],
      parking="Gate car park, free after 5pm.", transit="Bus 22 to Cooper’s Gate.", access="Step-free terrace and dining room.",
      booking="call", provider=""),
  ],
)

PRESS = ["The Old Town Courier", "Harbour & Hearth", "Table Talk Weekly", "The Lantern Review", "Good Food Almanac"]
